services:
  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "1000:1000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
